<a href="https://colab.research.google.com/github/khushimittal0108/adhocnw_machinelearning/blob/Data-Processing/numpypractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
#declare a 1-D array
a=np.array([2,4,6,8,5,9])

In [3]:
type(a)

numpy.ndarray

In [4]:
#display the array
a

array([2, 4, 6, 8, 5, 9])

In [0]:
b=np.array([5,6,4,3,8,2])

In [6]:
type(b)

numpy.ndarray

In [7]:
b

array([5, 6, 4, 3, 8, 2])

In [8]:
#adding two array of same lenght
a+b


array([ 7, 10, 10, 11, 13, 11])

In [9]:
#display particular element of array
a[2]

6

In [10]:
a[-2]+2

7

In [11]:
#adding a number to each element 
a+2

array([ 4,  6,  8, 10,  7, 11])

In [12]:
#multipying by a constant number
a*2

array([ 4,  8, 12, 16, 10, 18])

In [13]:
#squaring the elements
a**2

array([ 4, 16, 36, 64, 25, 81])

In [14]:
#cube the elements
a**3

array([  8,  64, 216, 512, 125, 729])

In [0]:
#declaring a 2-D array
d=np.array([[2,4,6],[6,8,1],[5,9,7],[3,9,7]])

In [16]:
#displaying the 2-D array
d

array([[2, 4, 6],
       [6, 8, 1],
       [5, 9, 7],
       [3, 9, 7]])

In [17]:
#to view the dimensions of array
d.shape

(4, 3)

In [18]:
#to view an element of 2-D array
d[2][1]

9

In [19]:
#to view a row of 2-D array
d[2]

array([5, 9, 7])

In [20]:
#adding a constant to all elements
d+2



array([[ 4,  6,  8],
       [ 8, 10,  3],
       [ 7, 11,  9],
       [ 5, 11,  9]])

In [21]:
#multiplying 2-D array by constant
d*2

array([[ 4,  8, 12],
       [12, 16,  2],
       [10, 18, 14],
       [ 6, 18, 14]])

In [22]:
#squaring the elements
d**2

array([[ 4, 16, 36],
       [36, 64,  1],
       [25, 81, 49],
       [ 9, 81, 49]])

In [23]:
#cube the elements
d**3

array([[  8,  64, 216],
       [216, 512,   1],
       [125, 729, 343],
       [ 27, 729, 343]])

In [0]:
e=np.array([[2,5,3,9],[3,7,6,1]])

In [25]:
e

array([[2, 5, 3, 9],
       [3, 7, 6, 1]])

In [26]:
e[0]

array([2, 5, 3, 9])

In [28]:
#display continuous rows 
#here 2 is excluded from range
d[0:2]  

array([[2, 4, 6],
       [6, 8, 1]])

In [29]:
#display all the rows starting from 0
d[0:]

array([[2, 4, 6],
       [6, 8, 1],
       [5, 9, 7],
       [3, 9, 7]])

In [30]:
#display all rows starting from 2
d[2:]

array([[5, 9, 7],
       [3, 9, 7]])

In [31]:
#display the elements of column 1 of selected row
d[2:,1]

array([9, 9])

In [32]:
#select continuous columns
d[0:,0:2]

array([[2, 4],
       [6, 8],
       [5, 9],
       [3, 9]])

In [33]:
d

array([[2, 4, 6],
       [6, 8, 1],
       [5, 9, 7],
       [3, 9, 7]])

In [35]:
#select particular row or column using square breackets
d[1,[0,2]]

array([6, 1])

In [36]:
d[[1,3],[0]]

array([6, 3])

In [37]:
d[[1,3],0:2]

array([[6, 8],
       [3, 9]])

In [38]:
d[[1,3],0:]

array([[6, 8, 1],
       [3, 9, 7]])

In [39]:
d[[1,3],0]

array([6, 3])

In [40]:
d[[0,2]]

array([[2, 4, 6],
       [5, 9, 7]])

In [41]:
d[[0,2],1]

array([4, 9])

In [42]:
d[[0,2],[1]]

array([4, 9])

In [44]:
#reshape the array into desired dimension
#remember the no. of elements should be same 
d.reshape(3,4)

array([[2, 4, 6, 6],
       [8, 1, 5, 9],
       [7, 3, 9, 7]])

In [45]:
d

array([[2, 4, 6],
       [6, 8, 1],
       [5, 9, 7],
       [3, 9, 7]])

In [46]:
#fill an array of given size with 0
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
#fill an array of given size with 1
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
#typecast the float to int
np.ones((4,8),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
#fill the array with desired number
np.full((6,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [50]:
#list of functions with 'ze'
for i in dir(np ):
  if 'ze' in i:
    print(i)

count_nonzero
digitize
flatnonzero
getbufsize
nonzero
resize
setbufsize
size
squeeze
trim_zeros
vectorize
zeros
zeros_like


In [51]:
[i for i in dir(np) if 'ze' in i ]

['count_nonzero',
 'digitize',
 'flatnonzero',
 'getbufsize',
 'nonzero',
 'resize',
 'setbufsize',
 'size',
 'squeeze',
 'trim_zeros',
 'vectorize',
 'zeros',
 'zeros_like']