<a href="https://colab.research.google.com/github/khushimittal0108/adhocnw_machinelearning/blob/master/pynumber1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [24]:
#method 1 to take input
r=int(input("Enter the number of rows :"))
c=int(input("Enter the number of columns :"))

Enter the number of rows :3
Enter the number of columns :7


In [0]:
arr=np.random.rand(r,c)

In [26]:
arr

array([[0.18340316, 0.243822  , 0.87431115, 0.46565003, 0.74084885,
        0.92749227, 0.41526782],
       [0.49250019, 0.24826168, 0.07172699, 0.98909746, 0.32422592,
        0.13348744, 0.47993039],
       [0.52729835, 0.15134431, 0.55813014, 0.64083777, 0.26947461,
        0.15551811, 0.66043455]])

In [0]:
np.save('array.npy',arr)

In [28]:
np.load('array.npy')

array([[0.18340316, 0.243822  , 0.87431115, 0.46565003, 0.74084885,
        0.92749227, 0.41526782],
       [0.49250019, 0.24826168, 0.07172699, 0.98909746, 0.32422592,
        0.13348744, 0.47993039],
       [0.52729835, 0.15134431, 0.55813014, 0.64083777, 0.26947461,
        0.15551811, 0.66043455]])

In [29]:
#method 2 to take input
row,column = input().split('x')

8x4


In [0]:
a=np.random.rand(int(row),int(column))


In [31]:
a

array([[0.65483227, 0.68523001, 0.93700268, 0.57668835],
       [0.65910998, 0.24093098, 0.07592156, 0.98758991],
       [0.9014004 , 0.15005507, 0.55870363, 0.39893771],
       [0.61835284, 0.16407245, 0.20894886, 0.76398447],
       [0.4058684 , 0.81850594, 0.9727068 , 0.5430668 ],
       [0.4206997 , 0.44254193, 0.37874387, 0.17889386],
       [0.75281614, 0.97832297, 0.38165237, 0.12529658],
       [0.72113001, 0.2546119 , 0.99652502, 0.82474089]])

In [0]:
np.save('array1.npy',a)

In [33]:
np.load('array1.npy')


array([[0.65483227, 0.68523001, 0.93700268, 0.57668835],
       [0.65910998, 0.24093098, 0.07592156, 0.98758991],
       [0.9014004 , 0.15005507, 0.55870363, 0.39893771],
       [0.61835284, 0.16407245, 0.20894886, 0.76398447],
       [0.4058684 , 0.81850594, 0.9727068 , 0.5430668 ],
       [0.4206997 , 0.44254193, 0.37874387, 0.17889386],
       [0.75281614, 0.97832297, 0.38165237, 0.12529658],
       [0.72113001, 0.2546119 , 0.99652502, 0.82474089]])