<a href="https://colab.research.google.com/github/khushimittal0108/adhocnw_machinelearning/blob/Data-Processing/pynumber2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
#for initializing the range of start of a 2-D array
x=np.arange(100,126,1)

In [31]:
#to print all the possible 2-D arrays
for i in x :
  y=np.arange(i,201,5)        #the end limit is 201 because the last value is excluded
  z=np.resize(y,(8,2))        #we have used resize() because the number of elements may be greater than 2x8 i.e.16
  print(z)

[[100 105]
 [110 115]
 [120 125]
 [130 135]
 [140 145]
 [150 155]
 [160 165]
 [170 175]]
[[101 106]
 [111 116]
 [121 126]
 [131 136]
 [141 146]
 [151 156]
 [161 166]
 [171 176]]
[[102 107]
 [112 117]
 [122 127]
 [132 137]
 [142 147]
 [152 157]
 [162 167]
 [172 177]]
[[103 108]
 [113 118]
 [123 128]
 [133 138]
 [143 148]
 [153 158]
 [163 168]
 [173 178]]
[[104 109]
 [114 119]
 [124 129]
 [134 139]
 [144 149]
 [154 159]
 [164 169]
 [174 179]]
[[105 110]
 [115 120]
 [125 130]
 [135 140]
 [145 150]
 [155 160]
 [165 170]
 [175 180]]
[[106 111]
 [116 121]
 [126 131]
 [136 141]
 [146 151]
 [156 161]
 [166 171]
 [176 181]]
[[107 112]
 [117 122]
 [127 132]
 [137 142]
 [147 152]
 [157 162]
 [167 172]
 [177 182]]
[[108 113]
 [118 123]
 [128 133]
 [138 143]
 [148 153]
 [158 163]
 [168 173]
 [178 183]]
[[109 114]
 [119 124]
 [129 134]
 [139 144]
 [149 154]
 [159 164]
 [169 174]
 [179 184]]
[[110 115]
 [120 125]
 [130 135]
 [140 145]
 [150 155]
 [160 165]
 [170 175]
 [180 185]]
[[111 116]
 [121 126]